import type { Employee, EmployeeId, JobStatus, Platform } from "./types";

export const EMPLOYEES: Employee[] = [
  {
    id: "researcher",
    number: "01",
    dept: "RESEARCH DEPT.",
    title: "THE RESEARCHER",
    tagline: "It finds every viral opportunity.",
    color: "#3B6FF5",
    colorSoft: "#E8EFFE",
    engine: "claude",
    capabilities: [
      { icon: "⌕", title: "TRACKS COMPETITORS", desc: "Monitors top creators and brands." },
      { icon: "↗", title: "FINDS TRENDS", desc: "Spots patterns before they go viral." },
      { icon: "⚑", title: "SAVES VIRAL POSTS", desc: "Collects high-performing content." },
      { icon: "◎", title: "FINDS NEW NICHES", desc: "Discovers untapped opportunities." },
    ],
    delivers: ["TREND REPORTS", "CONTENT IDEAS", "VIRAL REFERENCES", "OPPORTUNITY LISTS"],
    steps: [
      { title: "DISCOVER", desc: "Find opportunities everywhere." },
      { title: "COLLECT", desc: "Gather the best insights." },
      { title: "REPORT", desc: "Deliver actionable recommendations." },
    ],
  },
  {
    id: "hook",
    number: "02",
    dept: "HOOK DEPT.",
    title: "THE HOOK WRITER",
    tagline: "It owns the first two seconds.",
    color: "#C4784A",
    colorSoft: "#F8EDE4",
    engine: "claude",
    capabilities: [
      { icon: "✎", title: "WRITES OPENINGS", desc: "Ten options for every idea." },
      { icon: "#", title: "LEADS WITH PROOF", desc: "Numbers beat promises." },
      { icon: "✂", title: "KILLS WEAK LINES", desc: "Generic dies in the draft." },
      { icon: "⧉", title: "MATCHES THE FORMAT", desc: "Hooks tuned per platform." },
    ],
    delivers: ["HOOKS PER IDEA", "OPENING LINES", "TITLE VARIANTS", "THUMBNAIL TEXT"],
    steps: [
      { title: "DRAFT", desc: "Ten openings, fast." },
      { title: "CUT", desc: "Keep what stops thumbs." },
      { title: "HAND OFF", desc: "Winner goes to script." },
    ],
  },
  {
    id: "script",
    number: "03",
    dept: "SCRIPT DEPT.",
    title: "THE SCRIPT WRITER",
    tagline: "Every word is planned.",
    color: "#C9A227",
    colorSoft: "#F8F1D4",
    engine: "claude",
    capabilities: [
      { icon: "▤", title: "STRUCTURED DRAFTS", desc: "Scripts that convert." },
      { icon: "✶", title: "CLAUDE REFINE", desc: "Every word tightened." },
      { icon: "◉", title: "VOICE NOTES IN", desc: "Ideas captured. Scripts expanded." },
      { icon: "▷", title: "TELEPROMPTER READY", desc: "Smooth delivery. Perfect pacing." },
    ],
    delivers: ["REELS SCRIPTS", "CAROUSEL SCRIPTS", "YOUTUBE SCRIPTS", "CAPTIONS & CTAs", "HASHTAG PACKS"],
    steps: [
      { title: "IDEA", desc: "Capture the idea." },
      { title: "OUTLINE", desc: "Structure the message." },
      { title: "WRITE", desc: "Craft the script with AI." },
      { title: "REFINE", desc: "Polish for clarity and impact." },
      { title: "DELIVER", desc: "Ready to record and post." },
    ],
  },
  {
    id: "designer",
    number: "04",
    dept: "DESIGN DEPT.",
    title: "THE DESIGNER",
    tagline: "It designs every post.",
    color: "#6B5CFF",
    colorSoft: "#EEEBFF",
    engine: "both",
    capabilities: [
      { icon: "▣", title: "VISUAL BRIEF", desc: "Layouts, carousels & hierarchy." },
      { icon: "◆", title: "GROK IMAGINE", desc: "Covers, thumbnails & stills." },
      { icon: "◈", title: "BRAND SYSTEM", desc: "Ink, blue, accent, type." },
      { icon: "▤", title: "EXPORT READY", desc: "Assets sized per platform." },
    ],
    delivers: ["CAROUSEL DESIGNS", "THUMBNAILS THAT CTR", "REEL COVERS", "BRAND ASSETS", "TEMPLATES & MOCKUPS"],
    steps: [
      { title: "BRIEF", desc: "Understand the goal." },
      { title: "CONCEPT", desc: "Create visual directions." },
      { title: "DESIGN", desc: "Build high-impact visuals." },
      { title: "REVISE", desc: "Refine until it pops." },
      { title: "DELIVER", desc: "Export ready to post." },
    ],
  },
  {
    id: "analyst",
    number: "05",
    dept: "DATA DEPT.",
    title: "THE ANALYST",
    tagline: "It tells me what actually worked.",
    color: "#2F9E6A",
    colorSoft: "#E3F6EC",
    engine: "claude",
    capabilities: [
      { icon: "▤", title: "FINDS WINNERS", desc: "Identifies top performing content." },
      { icon: "⇄", title: "COMPARES COMPETITORS", desc: "Benchmarks against top creators." },
      { icon: "↻", title: "LEARNS PATTERNS", desc: "Discovers what gets views and followers." },
      { icon: "⤷", title: "IMPROVES STRATEGY", desc: "Turns data into better content." },
    ],
    delivers: ["VIEWS & IMPRESSIONS", "RETENTION & WATCH TIME", "SHARES & SAVES", "COMMENTS & ENGAGEMENT", "FOLLOWER GROWTH"],
    steps: [
      { title: "TRACK", desc: "Collect data from every platform." },
      { title: "ANALYZE", desc: "Find patterns in what worked." },
      { title: "LEARN", desc: "Extract insights that matter." },
      { title: "OPTIMIZE", desc: "Apply learnings to better content." },
    ],
  },
  {
    id: "manager",
    number: "06",
    dept: "OPERATIONS.",
    title: "THE MANAGER",
    tagline: "It runs the whole company.",
    color: "#B85C4A",
    colorSoft: "#F6E6E2",
    engine: "claude",
    capabilities: [
      { icon: "▦", title: "PLANS CONTENT", desc: "Schedules what gets created." },
      { icon: "☰", title: "MANAGES TEAM", desc: "Assigns tasks and keeps it moving." },
      { icon: "☀", title: "AUTOMATES FLOW", desc: "Connects systems and saves time." },
      { icon: "☑", title: "TRACKS PROGRESS", desc: "Monitors every employee's output." },
      { icon: "✈", title: "PUBLISHES DAILY", desc: "Posts on time. Every time." },
    ],
    delivers: ["EVERYTHING CONNECTED", "EVERYTHING AUTOMATED", "ONE SOURCE OF TRUTH"],
    steps: [
      { title: "RESEARCH", desc: "Queue ideas." },
      { title: "HOOKS", desc: "Pick winners." },
      { title: "SCRIPTS", desc: "Lock copy." },
      { title: "DESIGN", desc: "Ship visuals." },
      { title: "PUBLISH", desc: "Go live." },
      { title: "ANALYZE", desc: "Learn." },
      { title: "REPEAT", desc: "Close the loop." },
    ],
  },
  {
    id: "publisher",
    number: "07",
    dept: "PUBLISHING.",
    title: "THE PUBLISHER",
    tagline: "It posts. On time. Every time.",
    color: "#3A7D8C",
    colorSoft: "#E3F1F4",
    engine: "claude",
    capabilities: [
      { icon: "▦", title: "SCHEDULES CONTENT", desc: "Plans posts at peak times." },
      { icon: "⇄", title: "CROSS-PLATFORM", desc: "Publishes across all major platforms." },
      { icon: "▤", title: "OPTIMIZES CAPTIONS", desc: "Engaging captions designed to perform." },
      { icon: "✈", title: "CONSISTENT DELIVERY", desc: "Never late. Never loses momentum." },
      { icon: "☑", title: "TRACKS POST STATUS", desc: "Confirms, logs, and reports results." },
    ],
    delivers: ["ON TIME EVERY TIME", "REACH ACROSS PLATFORMS", "CONSISTENT GROWTH", "ZERO MANUAL MISSES", "COMPLETE REPORTS"],
    steps: [
      { title: "PLAN", desc: "Review calendar and content." },
      { title: "SCHEDULE", desc: "Set time, date, platforms." },
      { title: "PUBLISH", desc: "Post across platforms." },
      { title: "CONFIRM", desc: "Track status in real-time." },
      { title: "REPORT", desc: "Log results and insights." },
    ],
  },
];

export const PIPELINE: { id: JobStatus; label: string; employee?: EmployeeId }[] = [
  { id: "research", label: "RESEARCH", employee: "researcher" },
  { id: "hook", label: "HOOK", employee: "hook" },
  { id: "script", label: "SCRIPT", employee: "script" },
  { id: "design", label: "DESIGN", employee: "designer" },
  { id: "analyze", label: "ANALYZE", employee: "analyst" },
  { id: "plan", label: "PLAN", employee: "manager" },
  { id: "publish", label: "PUBLISH", employee: "publisher" },
];

export const PLATFORMS: { id: Platform; label: string }[] = [
  { id: "reels", label: "IG Reels" },
  { id: "tiktok", label: "TikTok" },
  { id: "shorts", label: "YT Shorts" },
  { id: "x", label: "X" },
  { id: "linkedin", label: "LinkedIn" },
  { id: "reddit", label: "Reddit" },
];

export function employeeById(id: EmployeeId) {
  return EMPLOYEES.find((e) => e.id === id)!;
}
